// nuxt-vue-ssr/app.vue
<template>
  <div class="app">
    <Header />
    <Content 
      :message="message"
      :data="data"
      :loading="pending"
      :error="error"
      @refresh-message="refreshMessage"
      @refresh-data="refreshData"
    />
    <Footer />
  </div>
</template>

<script setup lang="ts">
import type { ApiMessage, ApiData } from '~/types/api'

// Server-side data fetching
const { data: message } = await useFetch<ApiMessage>('/api/message')
const { data: data, pending, error, refresh: refreshData } = await useFetch<ApiData>('/api/data')

const refreshMessage = async () => {
  await refresh()
}

const refresh = async () => {
  await $fetch('/api/message')
}
</script>

<style scoped>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
</style>

// nextjs-react-ssr/src/app/page.tsx
import { Header } from '@/components/Header'
import { Content } from '@/components/Content'
import { Footer } from '@/components/Footer'
import { MessageService } from '@/services/MessageService'
import { DataService } from '@/services/DataService'
import type { ApiMessage, ApiData } from '@/types/api'

export default async function HomePage() {
  // Server-side data fetching
  let message: ApiMessage | null = null
  let data: ApiData | null = null
  let error: string | null = null

  try {
    [message, data] = await Promise.all([
      MessageService.getMessage(),
      DataService.getData()
    ])
  } catch (err) {
    error = 'Failed to fetch data from API'
    console.error('Error fetching data:', err)
  }

  return (
    <div className="app">
      <Header />
      <Content 
        message={message}
        data={data}
        loading={false}
        error={error}
        onRefreshMessage={async () => {
          'use server'
          // Server action for refreshing data
        }}
        onRefreshData={async () => {
          'use server'
          // Server action for refreshing data
        }}
      />
      <Footer />
    </div>
  )
}
